import { Platform, StyleSheet, ViewStyle } from 'react-native';
import { LAYOUT } from '../../constants/layout';
import { shadow } from '../../utils/shadowStyles';

/** `minHeight: '100vh' | '100%'` is a web-only CSS value that RN's `ViewStyle`
 * types as `number`. We keep the value but cast once to avoid widening the
 * entire `StyleSheet.create` inference into the `ViewStyle | TextStyle | ImageStyle` union. */
const container: ViewStyle = {
  flex: 1,
  ...(Platform.OS === 'web' && ({ minHeight: '100vh' } as unknown as ViewStyle)),
};
const map: ViewStyle = {
  flex: 1,
  ...(Platform.OS === 'web' && ({ minHeight: '100%' } as unknown as ViewStyle)),
};

export const mapStyles = StyleSheet.create({
  container,
  map,

  banner: {
    position: 'absolute', top: 0, left: 0, right: 0,
    backgroundColor: '#2E86AB',
    paddingVertical: 14, paddingHorizontal: 20,
    alignItems: 'center', zIndex: 100,
    ...shadow({ offset: { width: 0, height: 3 }, opacity: 0.2, radius: 6, elevation: 8 }),
  },
  bannerText: { color: '#fff', fontSize: 18, fontWeight: '700', textAlign: 'center' },

  topBar: {
    position: 'absolute',
    top: LAYOUT.headerTop,
    left: 12, right: 12,
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
  },
  iconBtn: {
    width: 44, height: 44, borderRadius: 22,
    backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center',
    ...shadow({ offset: { width: 0, height: 2 }, opacity: 0.15, radius: 6, elevation: 4 }),
  },
  menuIcon: { fontSize: 22, color: '#1A3A5C' },
  topBarAvatarImage: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  topBarAvatarText: {
    fontSize: 14,
    color: '#1A3A5C',
    fontWeight: '800',
  },
  statusPill: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: '#fff', borderRadius: 20,
    paddingHorizontal: 14, paddingVertical: 8,
    ...shadow({ offset: { width: 0, height: 2 }, opacity: 0.15, radius: 6, elevation: 4 }),
  },
  statusDot: { width: 9, height: 9, borderRadius: 5, marginLeft: 6 },
  statusText: { fontSize: 13, color: '#1A3A5C', fontWeight: '600' },

  centerBtn: {
    position: 'absolute', bottom: 110, right: 14,
    width: 46, height: 46, borderRadius: 23,
    backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center',
    zIndex: 20,
    pointerEvents: 'auto',
    ...shadow({ offset: { width: 0, height: 2 }, opacity: 0.15, radius: 6, elevation: 4 }),
  },
  centerBtnText: { fontSize: 22 },

  markerContainer: {
    width: 38, height: 38, borderRadius: 19,
    alignItems: 'center', justifyContent: 'center',
    ...shadow({ offset: { width: 0, height: 2 }, opacity: 0.3, radius: 4, elevation: 4 }),
    borderWidth: 2, borderColor: '#fff',
  },
  markerEmoji: { fontSize: 18 },

  categoryBar: {
    position: 'absolute', bottom: 0, left: 0, right: 0,
    backgroundColor: '#fff',
    paddingVertical: 12,
    paddingBottom: LAYOUT.categoryBarPaddingBottom,
    ...shadow({ offset: { width: 0, height: -3 }, opacity: 0.1, radius: 8, elevation: 10 }),
  },
  categoryBarContent: { paddingHorizontal: 14, gap: 8 },
  categoryChip: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 22, borderWidth: 1.5, borderColor: '#E5E7EB',
    paddingHorizontal: 12, paddingVertical: 8, marginRight: 8,
    gap: 6,
  },
  categoryChipEmoji: { fontSize: 17 },
  categoryChipText: { fontSize: 14, fontWeight: '600', color: '#374151' },
  categoryChipTextActive: { color: '#fff' },
  categoryChipBadge: {
    borderRadius: 10, paddingHorizontal: 7, paddingVertical: 2,
  },
  categoryChipBadgeActive: { backgroundColor: 'rgba(255,255,255,0.3)' },
  categoryChipBadgeText: { fontSize: 12, fontWeight: '700' },

  overlayContainer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 200,
    justifyContent: 'flex-end',
  },
  overlayBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.35)',
    zIndex: 0,
  },
  tapOptionsSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 40,
    zIndex: 201,
    ...shadow({ offset: { width: 0, height: -4 }, opacity: 0.15, radius: 12, elevation: 20 }),
  },
  tapOptionsHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#D1D5DB',
    alignSelf: 'center',
    marginBottom: 16,
  },
  tapOptionsTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1A3A5C',
    textAlign: 'center',
    marginBottom: 16,
  },
  tapOptionBtn: {
    backgroundColor: '#2E86AB',
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 10,
  },
  tapOptionBtnSecondary: {
    backgroundColor: '#F3F4F6',
  },
  tapOptionBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  tapOptionBtnTextSecondary: { color: '#1A3A5C', fontSize: 16, fontWeight: '600' },
  tapOptionCancel: {
    alignItems: 'center',
    paddingVertical: 12,
    marginTop: 8,
  },
  tapOptionCancelText: { color: '#6B7280', fontSize: 14 },

  guestHint: {
    fontSize: 13,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 8,
  },

  sheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24, borderTopRightRadius: 24,
    maxHeight: '65%',
    zIndex: 201,
    ...shadow({ offset: { width: 0, height: -4 }, opacity: 0.15, radius: 12, elevation: 20 }),
  },
  sheetHandle: {
    width: 40, height: 4, borderRadius: 2,
    backgroundColor: '#D1D5DB',
    alignSelf: 'center', marginTop: 10,
  },
  sheetHeader: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sheetHeaderLeadingSpacer: { width: 36, height: 36 },
  sheetBackBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#EEF2F7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetBackBtnText: { fontSize: 22, color: '#374151', fontWeight: '700', marginTop: -2 },
  sheetCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetCloseBtnText: { fontSize: 14, color: '#6B7280', fontWeight: '700' },
  sheetTitleRow: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 10 },
  sheetTitleTextCol: { flex: 1, alignItems: 'flex-end' },
  sheetTitleEmoji: { fontSize: 30 },
  sheetTitle: { fontSize: 18, fontWeight: '800', color: '#1A3A5C', textAlign: 'right' },
  sheetSubtitle: { fontSize: 12, color: '#6B7280', textAlign: 'right', marginTop: 2 },
  sheetEmpty: { padding: 40, alignItems: 'center' },
  sheetEmptyText: { color: '#9CA3AF', fontSize: 15 },
  sheetList: { padding: 16, paddingBottom: 30 },
  sheetTreeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  sheetTreeItemEmoji: { fontSize: 22, marginLeft: 12 },
  sheetTreeItemText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
    textAlign: 'right',
  },
  sheetTreeItemChevron: { fontSize: 20, color: '#9CA3AF', marginRight: 4 },

  catStoreItem: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: '#F8FAFC', borderRadius: 14,
    padding: 14, marginBottom: 10,
    ...shadow({ offset: { width: 0, height: 1 }, opacity: 0.06, radius: 4, elevation: 2 }),
  },
  catStoreLeft: { marginLeft: 12 },
  catStoreDistanceBadge: {
    borderRadius: 10, paddingHorizontal: 10, paddingVertical: 5,
    minWidth: 60, alignItems: 'center',
  },
  catStoreDistanceText: { fontSize: 13, fontWeight: '700' },
  catStoreInfo: { flex: 1, alignItems: 'flex-end' },
  catStoreName: { fontSize: 15, fontWeight: '700', color: '#1F2937', textAlign: 'right' },
  catStoreDesc: { fontSize: 12, color: '#6B7280', textAlign: 'right', marginTop: 3 },
  catStorePhone: { fontSize: 12, color: '#4A7FA5', marginTop: 3 },
  catStoreEmoji: { fontSize: 26, marginLeft: 14 },

  sidebar: {
    position: 'absolute',
    right: 0, top: 0, bottom: 0,
    width: '80%',
    maxWidth: 340,
    backgroundColor: '#fff',
    zIndex: 201,
    ...shadow({ offset: { width: -4, height: 0 }, opacity: 0.2, radius: 12, elevation: 20 }),
  },
  sidebarHeader: {
    backgroundColor: '#2E86AB', padding: 24,
    paddingTop: LAYOUT.sidebarHeaderTop, alignItems: 'center',
  },
  avatarCircle: {
    width: 60, height: 60, borderRadius: 30,
    backgroundColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center', justifyContent: 'center', marginBottom: 10,
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  avatarText: { fontSize: 26, color: '#fff', fontWeight: '700' },
  sidebarName: { color: '#fff', fontSize: 18, fontWeight: '700', textAlign: 'center' },
  sidebarEmail: { color: 'rgba(255,255,255,0.8)', fontSize: 13, marginTop: 2, textAlign: 'center' },
  adminBadge: {
    backgroundColor: '#F59E0B', borderRadius: 12,
    paddingHorizontal: 12, paddingVertical: 4, marginTop: 8,
  },
  adminBadgeText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  sidebarList: { flex: 1, padding: 16 },
  sidebarSectionTitle: {
    fontSize: 14, fontWeight: '700', color: '#1A3A5C',
    textAlign: 'right', marginBottom: 12,
  },
  sidebarCatGrid: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 10,
  },
  sidebarCatItem: {
    width: '31%',
    minHeight: 88,
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 8,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'space-between',
    ...shadow({ offset: { width: 0, height: 1 }, opacity: 0.06, radius: 4, elevation: 2 }),
  },
  sidebarCatEmoji: { fontSize: 20 },
  sidebarCatName: {
    marginTop: 5,
    marginBottom: 7,
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '700',
    color: '#1F2937',
  },
  sidebarCatCount: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    minWidth: 34,
    alignItems: 'center',
  },
  sidebarCatCountText: { fontSize: 13, fontWeight: '700' },
  sidebarAdminBtn: {
    margin: 16, marginBottom: 8,
    backgroundColor: '#1A3A5C', borderRadius: 12, padding: 14, alignItems: 'center',
  },
  sidebarAdminBtnText: { color: '#fff', fontWeight: '700', fontSize: 15 },
  sidebarUserModBtn: {
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 8,
    backgroundColor: '#E0F2FE',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#BAE6FD',
    padding: 14,
    alignItems: 'center',
  },
  sidebarUserModBtnText: { color: '#075985', fontWeight: '700', fontSize: 15 },
  logoutBtn: {
    margin: 16, marginTop: 8,
    backgroundColor: '#FEE2E2', borderRadius: 12, padding: 14, alignItems: 'center',
  },
  logoutBtnText: { color: '#EF4444', fontWeight: '700', fontSize: 15 },

  routeBanner: {
    position: 'absolute',
    top: LAYOUT.headerTop + 56,
    left: 12, right: 12,
    zIndex: 90,
  },
  routeBannerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 12,
    ...shadow({ offset: { width: 0, height: 2 }, opacity: 0.15, radius: 8, elevation: 6 }),
  },
  routeBannerInfo: {
    flex: 1,
    flexDirection: 'row',
    gap: 16,
    justifyContent: 'center',
  },
  routeBannerDistance: { fontSize: 15, fontWeight: '700', color: '#1A3A5C' },
  routeBannerDuration: { fontSize: 15, fontWeight: '600', color: '#6B7280' },
  routeBannerClose: {
    backgroundColor: '#FEE2E2',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  routeBannerCloseText: { color: '#DC2626', fontSize: 13, fontWeight: '700' },

  storeModal: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    overflow: 'hidden',
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 201,
    ...shadow({ offset: { width: 0, height: -6 }, opacity: 0.18, radius: 16, elevation: 24 }),
  },
  storeModalHandle: {
    width: 40, height: 4, borderRadius: 2,
    backgroundColor: '#D1D5DB',
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 4,
  },
  storeModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 4,
    gap: 8,
  },
  /** نفس الرأس لكن معكوس للـ LTR حتى يبقى: أيقونة يسار، اسم وسط، إغلاق يمين */
  storeModalHeaderLtr: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 4,
    gap: 8,
  },
  storeModalHeaderTitleWrap: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  storeModalHeaderTitle: {
    fontSize: 21,
    fontWeight: '800',
    color: '#1A3A5C',
    textAlign: 'right',
    lineHeight: 28,
  },
  storeModalHeaderEmojiSpacer: {
    width: 72,
    height: 72,
  },
  storeModalEmojiCircle: {
    width: 72, height: 72, borderRadius: 36,
    alignItems: 'center', justifyContent: 'center',
  },
  storeModalEmoji: { fontSize: 38 },
  closeModalBtn: {
    width: 34, height: 34, borderRadius: 17,
    backgroundColor: '#F3F4F6',
    alignItems: 'center', justifyContent: 'center',
  },
  closeModalBtnText: { color: '#6B7280', fontSize: 16, fontWeight: '700' },
  storeModalBody: { padding: 20, paddingTop: 8, alignItems: 'flex-end' },
  storeModalName: {
    fontSize: 22, fontWeight: '800', color: '#1A3A5C',
    textAlign: 'right', marginBottom: 10,
    alignSelf: 'stretch',
  },
  storeModalPillsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'stretch',
    width: '100%',
    gap: 8,
    marginBottom: 12,
  },
  storeModalPillsGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  /** بحجم شارة المسافة/النوع — بدون تمدد بعرض الصف */
  storeModalCurrentCoordsBox: {
    alignSelf: 'center',
    maxWidth: '100%',
    borderWidth: 1,
    borderColor: '#F87171',
    backgroundColor: '#FEE2E2',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  storeModalCurrentCoordsText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#991B1B',
    textAlign: 'right',
  },
  storeModalCategoryPill: {
    borderRadius: 20,
    paddingHorizontal: 14, paddingVertical: 6,
  },
  storeModalCategoryText: { fontSize: 13, fontWeight: '700' },
  storeModalDistancePill: {
    backgroundColor: '#DCFCE7', borderRadius: 20,
    paddingHorizontal: 14, paddingVertical: 6,
    flexDirection: 'row', alignItems: 'center', gap: 4,
  },
  storeModalDistanceText: { color: '#16A34A', fontSize: 13, fontWeight: '700' },
  storeModalDescription: {
    fontSize: 14, color: '#4B5563', textAlign: 'right',
    lineHeight: 22, marginBottom: 12,
    alignSelf: 'stretch',
  },
  storeModalPhoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: '#F0F9FF',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 16,
    gap: 8,
  },
  storeModalPhoneIcon: { fontSize: 18 },
  storeModalPhoneText: { fontSize: 15, fontWeight: '700', color: '#2E86AB' },
  storeModalBtnRow: {
    flexDirection: 'row-reverse',
    gap: 10,
    alignSelf: 'stretch',
    marginBottom: 14,
    alignItems: 'stretch',
  },
  storeModalCallBtn: {
    flex: 1,
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#16A34A',
    borderWidth: 1,
    borderColor: '#15803D',
    ...shadow({ color: '#166534', offset: { width: 0, height: 4 }, opacity: 0.24, radius: 8, elevation: 4 }),
  },
  storeModalCallBtnIconWrap: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 3,
  },
  storeModalCallBtnIcon: { fontSize: 13 },
  storeModalCallBtnLabel: { color: 'rgba(255,255,255,0.9)', fontSize: 11, fontWeight: '700' },
  storeModalCallBtnText: { color: '#fff', fontSize: 14, fontWeight: '900', marginTop: 1 },
  storeModalActionBtn: {
    flex: 1,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  storeModalNavigateBtn: {
    backgroundColor: '#2E86AB',
    ...shadow({ offset: { width: 0, height: 2 }, opacity: 0.2, radius: 6, elevation: 4 }),
  },
  storeModalNavigateBtnIcon: { fontSize: 22, marginBottom: 4 },
  storeModalNavigateBtnText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  storeModalNavigateBtnSub: {
    color: 'rgba(255,255,255,0.75)', fontSize: 11, fontWeight: '600', marginTop: 2,
  },
  travelModeBody: { padding: 20, paddingTop: 6, alignItems: 'stretch', gap: 14 },
  travelModeTitle: { fontSize: 18, fontWeight: '900', color: '#1A3A5C', textAlign: 'right' },
  travelModeSubtitle: { fontSize: 13, color: '#6B7280', textAlign: 'right', marginTop: -8 },
  travelModeGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginTop: 4 },
  travelModeOptionBtn: {
    flexBasis: '48%',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadow({ offset: { width: 0, height: 2 }, opacity: 0.18, radius: 6, elevation: 4 }),
    marginBottom: 12,
  },
  travelModeOptionText: { color: '#fff', fontSize: 14, fontWeight: '900' },
  travelBackBtn: { backgroundColor: '#F3F4F6', borderRadius: 14, paddingVertical: 12, alignItems: 'center', justifyContent: 'center' },
  travelBackBtnText: { color: '#374151', fontSize: 14, fontWeight: '800' },

  travelPreviewBody: { padding: 20, paddingTop: 8, alignItems: 'stretch', gap: 14 },
  travelPreviewTitle: { fontSize: 18, fontWeight: '900', color: '#1A3A5C', textAlign: 'right' },
  travelPreviewSubtitle: { fontSize: 13, color: '#6B7280', textAlign: 'right' },
  travelInfoBlock: {
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#EEF2F7',
  },
  travelInfoLabel: { fontSize: 12, color: '#6B7280', fontWeight: '700', marginBottom: 6 },
  travelInfoValue: { fontSize: 13, color: '#111827', fontWeight: '800' },
  travelLoadingText: { textAlign: 'right', color: '#6B7280', fontWeight: '700' },
  travelDurationBox: { backgroundColor: '#fff', borderRadius: 14, padding: 14, ...shadow({ offset: { width: 0, height: 1 }, opacity: 0.08, radius: 6, elevation: 2 }) },
  travelDurationLine: { fontSize: 14, fontWeight: '900', color: '#1A3A5C' },
  travelDurationLine2: { fontSize: 13, fontWeight: '700', color: '#6B7280', marginTop: 6 },
  travelPreviewBtnsRow: { flexDirection: 'row', gap: 12, marginTop: 4 },
  travelPreviewBtn: { flex: 1, borderRadius: 14, paddingVertical: 12, alignItems: 'center', justifyContent: 'center' },
  travelCancelBtn: { backgroundColor: '#FEF3C7' },
  travelConfirmBtn: { backgroundColor: '#2E86AB' },
  travelPreviewBtnTextCancel: { color: '#B45309', fontSize: 14, fontWeight: '900' },
  travelPreviewBtnTextConfirm: { color: '#fff', fontSize: 14, fontWeight: '900' },
  storeModalServicesBtn: {
    backgroundColor: '#F3F4F6',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
  },
  storeModalServicesBtnIcon: { fontSize: 22, marginBottom: 4 },
  storeModalServicesBtnText: { color: '#374151', fontSize: 14, fontWeight: '700' },

  storeModalReportBtn: {
    backgroundColor: '#FEF3C7',
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
    alignSelf: 'stretch',
    marginBottom: 8,
  },
  storeModalReportBtnText: { color: '#B45309', fontSize: 13, fontWeight: '600' },

  storeModalAdminRow: {
    flexDirection: 'row', gap: 10, alignSelf: 'stretch', marginTop: 8,
  },
  storeModalEditBtn: {
    flex: 1, backgroundColor: '#2E86AB', borderRadius: 12,
    paddingVertical: 10, alignItems: 'center',
  },
  storeModalEditBtnText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  storeModalDeleteBtn: {
    flex: 1, backgroundColor: '#FEE2E2', borderRadius: 12,
    paddingVertical: 10, alignItems: 'center',
  },
  storeModalDeleteBtnText: { color: '#DC2626', fontSize: 13, fontWeight: '700' },

  placeSearchWrap: {
    position: 'absolute',
    top: LAYOUT.headerTop + 62,
    left: 12,
    right: 12,
    zIndex: 120,
  },
  placeSearchInputRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
    ...shadow({ offset: { width: 0, height: 2 }, opacity: 0.12, radius: 6, elevation: 6 }),
  },
  placeSearchInput: {
    flex: 1,
    fontSize: 14,
    color: '#1F2937',
    paddingVertical: 6,
    textAlign: 'right',
  },
  placeSearchClearBtn: {
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  placeSearchClearBtnText: { color: '#6B7280', fontSize: 16, fontWeight: '700' },

  placeSearchResultsCard: {
    marginTop: 10,
    backgroundColor: '#fff',
    borderRadius: 16,
    overflow: 'hidden',
    ...shadow({ offset: { width: 0, height: 2 }, opacity: 0.12, radius: 8, elevation: 10 }),
  },
  placeSearchEmpty: { padding: 22, alignItems: 'center' },
  placeSearchEmptyEmoji: { fontSize: 34, marginBottom: 8 },
  placeSearchEmptyText: { color: '#9CA3AF', fontSize: 14, fontWeight: '600' },
  placeSearchResults: { maxHeight: 260 },
  placeSearchResultsContent: { paddingHorizontal: 10, paddingVertical: 8 },
  placeSearchItem: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginBottom: 10,
  },
  placeSearchItemEmojiPill: {
    backgroundColor: 'rgba(46, 134, 171, 0.12)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginLeft: 10,
  },
  placeSearchItemEmoji: { fontSize: 18 },
  placeSearchItemMain: { flex: 1, minWidth: 0 },
  placeSearchItemName: { fontSize: 14, fontWeight: '800', color: '#111827', textAlign: 'right' },
  placeSearchItemMeta: { fontSize: 12, color: '#6B7280', fontWeight: '600', textAlign: 'right', marginTop: 2 },
  placeSearchItemPhone: { fontSize: 12, color: '#4A7FA5', fontWeight: '700', marginLeft: 12, maxWidth: 110 },
});
