import { StyleSheet } from 'react-native';
import { LAYOUT } from '../../constants/layout';
import { shadow } from '../../utils/shadowStyles';

export const adminUsersStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#E8EEF2' },
  centered: { alignItems: 'center', justifyContent: 'center' },
  unauthorized: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  unauthorizedText: { fontSize: 20, color: '#EF4444', marginBottom: 16 },
  backLink: { color: '#2E86AB', fontSize: 16 },
  header: {
    backgroundColor: '#1A3A5C',
    paddingTop: LAYOUT.headerTop,
    paddingBottom: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backBtnText: { color: '#fff', fontSize: 20 },
  headerTitle: { color: '#fff', fontSize: 20, fontWeight: '700', marginRight: 12 },
  headerBadge: { backgroundColor: '#F59E0B', borderRadius: 12, paddingHorizontal: 10, paddingVertical: 4 },
  headerBadgeText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  content: { flex: 1, padding: 16 },
  searchWrap: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingHorizontal: 14,
    marginBottom: 14,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    ...shadow({ offset: { width: 0, height: 1 }, opacity: 0.06, radius: 4, elevation: 2 }),
  },
  searchIcon: { fontSize: 18, marginLeft: 8 },
  searchInput: {
    flex: 1,
    paddingVertical: 12,
    fontSize: 15,
    color: '#1F2937',
    minHeight: 48,
  },
  loadingBlock: { alignItems: 'center', paddingTop: 48, gap: 12 },
  loadingText: { textAlign: 'center', color: '#6B7280', marginTop: 8, fontSize: 15 },
  errorState: { alignItems: 'center', paddingVertical: 40, paddingHorizontal: 20 },
  errorText: { fontSize: 16, color: '#EF4444', textAlign: 'center', marginBottom: 8 },
  errorHint: { fontSize: 13, color: '#6B7280', textAlign: 'center', marginBottom: 16 },
  retryBtn: { backgroundColor: '#2E86AB', paddingVertical: 10, paddingHorizontal: 20, borderRadius: 10 },
  retryBtnText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  list: { flex: 1 },
  listContent: { paddingBottom: 40 },
  userCard: {
    backgroundColor: '#fff',
    borderRadius: 18,
    marginBottom: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E8EDF2',
    ...shadow({ offset: { width: 0, height: 3 }, opacity: 0.07, radius: 10, elevation: 3 }),
  },
  cardTop: { flexDirection: 'row-reverse', alignItems: 'flex-start', gap: 14 },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#EBF5FB',
    borderWidth: 2,
    borderColor: '#2E86AB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarAdmin: { backgroundColor: '#FEF3C7', borderColor: '#F59E0B' },
  avatarImg: { width: 48, height: 48, borderRadius: 24 },
  avatarText: { fontSize: 20, fontWeight: '800', color: '#1A3A5C' },
  cardMain: { flex: 1, minWidth: 0 },
  nameRow: { flexDirection: 'row-reverse', alignItems: 'flex-start', gap: 8 },
  userName: {
    flex: 1,
    fontSize: 17,
    fontWeight: '800',
    color: '#111827',
    textAlign: 'right',
    lineHeight: 24,
  },
  rolePill: {
    backgroundColor: '#F59E0B',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    flexShrink: 0,
  },
  rolePillText: { color: '#fff', fontSize: 11, fontWeight: '800' },
  userEmail: { fontSize: 14, color: '#6B7280', marginTop: 6, textAlign: 'right', lineHeight: 20 },
  actionRow: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 10, marginTop: 16 },
  btn: {
    flexGrow: 1,
    minWidth: '28%',
    minHeight: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  btnEdit: { backgroundColor: '#EBF5FB', borderWidth: 1.5, borderColor: '#2E86AB' },
  btnEditText: { fontSize: 13, fontWeight: '800', color: '#2E86AB' },
  btnPromote: { backgroundColor: '#D1FAE5', borderWidth: 1, borderColor: '#A7F3D0' },
  btnDemote: { backgroundColor: '#FEF3C7', borderWidth: 1, borderColor: '#FCD34D' },
  btnMutedText: { fontSize: 13, fontWeight: '800', color: '#374151' },
  btnDelete: { backgroundColor: '#FEF2F2', borderWidth: 1, borderColor: '#FECACA' },
  btnDeleteText: { fontSize: 13, fontWeight: '800', color: '#B91C1C' },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: '#F8FAFC',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    maxHeight: '88%',
    paddingBottom: 24,
  },
  modalHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingTop: LAYOUT.modalHeaderTop,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    backgroundColor: '#fff',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
  },
  modalCancel: { color: '#EF4444', fontSize: 16, fontWeight: '600' },
  modalTitle: { fontSize: 17, fontWeight: '800', color: '#1A3A5C' },
  modalSave: { color: '#2E86AB', fontSize: 16, fontWeight: '800' },
  modalBody: { padding: 20 },
  fieldLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#374151',
    textAlign: 'right',
    marginBottom: 8,
    marginTop: 4,
  },
  fieldInput: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: '#1F2937',
    marginBottom: 6,
  },
  dobRow: { flexDirection: 'row-reverse', gap: 6, marginBottom: 6 },
  dobInput: {
    flex: 1,
    minWidth: 0,
    marginBottom: 0,
    paddingHorizontal: 8,
    paddingVertical: 10,
    fontSize: 14,
  },
  fieldDisabled: { backgroundColor: '#F3F4F6', color: '#6B7280' },
  fieldHint: { fontSize: 12, color: '#9CA3AF', textAlign: 'right', marginBottom: 8 },
  verifyRow: { flexDirection: 'row-reverse', gap: 8, marginBottom: 8 },
  verifyChip: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    paddingVertical: 9,
    alignItems: 'center',
  },
  verifyChipActiveVerified: { backgroundColor: '#DCFCE7', borderColor: '#4ADE80' },
  verifyChipActivePending: { backgroundColor: '#FEF3C7', borderColor: '#F59E0B' },
  verifyChipActiveRejected: { backgroundColor: '#FEE2E2', borderColor: '#F87171' },
  verifyChipText: { fontSize: 12, fontWeight: '700', color: '#475569' },
  verifyChipTextActiveVerified: { color: '#166534' },
  verifyChipTextActivePending: { color: '#92400E' },
  verifyChipTextActiveRejected: { color: '#B91C1C' },
  imageRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  editImagePreview: {
    width: 64,
    height: 64,
    borderRadius: 10,
    backgroundColor: '#E2E8F0',
  },
  editImagePlaceholder: {
    borderWidth: 1,
    borderColor: '#CBD5E1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  editImagePlaceholderText: { fontSize: 11, color: '#64748B', fontWeight: '600' },
  imageActions: { flex: 1, gap: 8 },
  inlineActionBtn: {
    backgroundColor: '#E0F2FE',
    borderWidth: 1,
    borderColor: '#7DD3FC',
    borderRadius: 10,
    paddingVertical: 8,
    alignItems: 'center',
  },
  inlineActionBtnText: { color: '#075985', fontSize: 12, fontWeight: '700' },
  inlineDangerBtn: { backgroundColor: '#FEF2F2', borderColor: '#FCA5A5' },
  inlineDangerBtnText: { color: '#B91C1C', fontSize: 12, fontWeight: '700' },
});
