import { StyleSheet } from 'react-native';
import { LAYOUT } from '../../constants/layout';
import { shadow } from '../../utils/shadowStyles';

export const adminStoresStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F0F4F8' },
  unauthorized: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  unauthorizedText: { fontSize: 20, color: '#EF4444', marginBottom: 16 },
  backLink: { color: '#2E86AB', fontSize: 16 },
  header: {
    backgroundColor: '#1A3A5C',
    paddingTop: LAYOUT.headerTop,
    paddingBottom: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backBtnText: { color: '#fff', fontSize: 20 },
  headerTitle: { color: '#fff', fontSize: 20, fontWeight: '700', marginRight: 12 },
  headerBadge: { backgroundColor: '#F59E0B', borderRadius: 12, paddingHorizontal: 10, paddingVertical: 4 },
  headerBadgeText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  content: { flex: 1, padding: 16 },
  unitsBtn: {
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginTop: 10,
    alignItems: 'center',
  },
  unitsBtnText: { color: '#1D4ED8', fontSize: 14, fontWeight: '800' },
  unitCard: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 14,
    padding: 12,
  },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 },
  sectionTitleRow: { flexDirection: 'row-reverse', alignItems: 'center', gap: 8 },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: '#1A3A5C', textAlign: 'right' },
  sectionCountBadge: {
    minWidth: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#E0F2FE',
    borderWidth: 1,
    borderColor: '#BAE6FD',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  sectionCountBadgeText: { color: '#0369A1', fontSize: 12, fontWeight: '800' },
  addBtn: { backgroundColor: '#2E86AB', borderRadius: 10, paddingVertical: 8, paddingHorizontal: 14 },
  addBtnText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  housesStatsRow: { flexDirection: 'row-reverse', gap: 8, marginBottom: 10 },
  housesStatChip: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    paddingVertical: 8,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  housesStatChipActive: { borderWidth: 2, borderColor: '#1A3A5C' },
  housesVisibleChip: { backgroundColor: '#ECFDF5', borderColor: '#A7F3D0' },
  housesHiddenChip: { backgroundColor: '#FEF2F2', borderColor: '#FECACA' },
  housesVisibleText: { color: '#065F46', fontSize: 13, fontWeight: '800' },
  housesHiddenText: { color: '#991B1B', fontSize: 13, fontWeight: '800' },
  searchInput: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 14,
    color: '#1F2937',
    marginBottom: 12,
  },
  list: { flex: 1 },
  listContent: { paddingBottom: 40 },
  emptyState: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 60 },
  emptyStateEmoji: { fontSize: 60, marginBottom: 16 },
  emptyStateText: { color: '#9CA3AF', fontSize: 16, marginBottom: 16 },
  emptyStateBtn: { backgroundColor: '#2E86AB', borderRadius: 12, paddingVertical: 12, paddingHorizontal: 24 },
  emptyStateBtnText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  storeCard: {
    backgroundColor: '#fff',
    borderRadius: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#E8EDF2',
    overflow: 'hidden',
    ...shadow({ offset: { width: 0, height: 3 }, opacity: 0.07, radius: 10, elevation: 3 }),
  },
  storeCardBody: { padding: 16 },
  storeCardTop: { flexDirection: 'row-reverse', alignItems: 'flex-start', gap: 14 },
  storeTypeIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  storeTypeIconEmoji: { fontSize: 26 },
  storeCardMain: { flex: 1, minWidth: 0, alignItems: 'flex-end' },
  storeCardName: { fontSize: 17, fontWeight: '800', color: '#111827', textAlign: 'right', lineHeight: 24 },
  storeCardDesc: { fontSize: 14, color: '#6B7280', textAlign: 'right', marginTop: 6, lineHeight: 20 },
  storeChipsRow: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  storeChip: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  storeChipText: { fontSize: 12, fontWeight: '700', textAlign: 'right' },
  storeChipMuted: {
    backgroundColor: '#F3F4F6',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  storeChipMutedText: { fontSize: 12, color: '#4B5563', fontWeight: '600', textAlign: 'right' },
  storeChipPhone: {
    backgroundColor: '#EBF5FB',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  storeChipPhoneText: { fontSize: 12, color: '#1D4ED8', fontWeight: '800', textAlign: 'right' },
  storeActionRow: {
    flexDirection: 'row-reverse',
    gap: 10,
    paddingHorizontal: 16,
    paddingBottom: 16,
    position: 'relative',
    zIndex: 10,
  },
  storeActionBtn: {
    flex: 1,
    minHeight: 46,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    zIndex: 11,
    pointerEvents: 'auto',
  },
  storeActionEdit: { backgroundColor: '#EBF5FB', borderWidth: 1.5, borderColor: '#2E86AB' },
  storeActionEditText: { fontSize: 14, fontWeight: '800', color: '#2E86AB' },
  storeActionDelete: { backgroundColor: '#FEF2F2', borderWidth: 1.5, borderColor: '#FECACA' },
  storeActionDeleteText: { fontSize: 14, fontWeight: '800', color: '#B91C1C' },
  storeActionHide: { backgroundColor: '#FFF7ED', borderWidth: 1.5, borderColor: '#FDBA74' },
  storeActionHideText: { fontSize: 14, fontWeight: '800', color: '#C2410C' },
  storeActionShow: { backgroundColor: '#ECFDF5', borderWidth: 1.5, borderColor: '#86EFAC' },
  storeActionShowText: { fontSize: 14, fontWeight: '800', color: '#166534' },
  modalContainer: { flex: 1, backgroundColor: '#F0F4F8' },
  modalHeader: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: LAYOUT.modalHeaderTop,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  modalCancelText: { color: '#EF4444', fontSize: 16, fontWeight: '600' },
  modalTitle: { color: '#1A3A5C', fontSize: 17, fontWeight: '700' },
  modalSaveText: { color: '#2E86AB', fontSize: 16, fontWeight: '700' },
  modalBody: { flex: 1, padding: 16 },
  formGroup: { marginBottom: 20 },
  formLabel: { fontSize: 14, fontWeight: '600', color: '#374151', textAlign: 'right', marginBottom: 8 },
  formInput: {
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 15,
    color: '#1F2937',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
  },
  formTextarea: { height: 90, paddingTop: 12 },
  chipsWrap: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 8 },
  photosWrap: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 8 },
  photoItemWrap: { position: 'relative' },
  photoThumb: { width: 74, height: 74, borderRadius: 10, borderWidth: 1, borderColor: '#E5E7EB' },
  photoDeleteBtn: {
    position: 'absolute',
    top: -6,
    left: -6,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoDeleteBtnText: { color: '#fff', fontSize: 12, fontWeight: '800' },
  addPhotoBtn: {
    marginTop: 10,
    alignSelf: 'flex-end',
    backgroundColor: '#EBF5FB',
    borderColor: '#BFDBFE',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  addPhotoBtnText: { color: '#1D4ED8', fontWeight: '700', fontSize: 13 },
  noPhotosText: { color: '#9CA3AF', fontSize: 13, textAlign: 'right' },
  categoryChip: { backgroundColor: '#E5E7EB', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 8, marginRight: 8 },
  categoryChipActive: { backgroundColor: '#2E86AB' },
  categoryChipText: { fontSize: 14, color: '#374151', fontWeight: '500' },
  categoryChipTextActive: { color: '#fff', fontWeight: '700' },
  categoryChipDisabled: { opacity: 0.55 },
  categoryChipTextDisabled: { color: '#6B7280' },
  categoryLockedHint: { marginTop: 6, color: '#6B7280', fontSize: 12, fontWeight: '700', textAlign: 'right' },
  coordsRow: { flexDirection: 'row', gap: 10 },
  coordInput: { flex: 1 },
  deleteBtn: { backgroundColor: '#FEE2E2', borderRadius: 12, paddingVertical: 14, alignItems: 'center', marginTop: 24 },
  deleteBtnText: { fontSize: 15, color: '#DC2626', fontWeight: '700' },
  boolToggle: { backgroundColor: '#F3F4F6', borderRadius: 12, padding: 14, alignItems: 'center', borderWidth: 1.5, borderColor: '#E5E7EB' },
  boolToggleActive: { backgroundColor: '#DCFCE7', borderColor: '#86EFAC' },
  boolToggleText: { fontSize: 15, fontWeight: '600', color: '#374151' },

  submitBtn: {
    marginTop: 12,
    backgroundColor: '#2E86AB',
    borderRadius: 12,
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitBtnDisabled: { opacity: 0.6 },
  submitBtnText: { color: '#fff', fontSize: 14, fontWeight: '800' },

  housesOverlay: { flex: 1, justifyContent: 'flex-end' },
  housesBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.35)' },
  housesSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    maxHeight: '82%',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  housesSheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  housesSheetTitle: { flex: 1, fontSize: 15, fontWeight: '900', color: '#111827', textAlign: 'center' },
  housesCloseText: { fontSize: 18, fontWeight: '900', color: '#111827' },
  housesErrorText: { padding: 14, color: '#B91C1C', fontWeight: '800', textAlign: 'right' },
  housesEmptyText: { padding: 14, color: '#6B7280', fontWeight: '800', textAlign: 'right' },
  housesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 10,
  },
  housesRowIcon: { fontSize: 18 },
  housesRowName: { flex: 1, fontSize: 14, fontWeight: '900', color: '#111827', textAlign: 'right' },
  housesRowArrow: { width: 20, textAlign: 'left', color: '#64748B', fontWeight: '900' },
  unitTypePickRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 10,
  },
});

