import { StyleSheet } from 'react-native';
import { LAYOUT } from '../../constants/layout';
import { shadow } from '../../utils/shadowStyles';

export const adminReportsStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F0F4F8' },
  unauthorized: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  unauthorizedText: { fontSize: 20, color: '#EF4444', marginBottom: 16 },
  backLink: { color: '#2E86AB', fontSize: 16 },
  header: {
    backgroundColor: '#1A3A5C',
    paddingTop: LAYOUT.headerTop,
    paddingBottom: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backBtnText: { color: '#fff', fontSize: 20 },
  headerTitle: { color: '#fff', fontSize: 20, fontWeight: '700', marginRight: 12 },
  headerBadge: { backgroundColor: '#EF4444', borderRadius: 12, paddingHorizontal: 10, paddingVertical: 4 },
  headerBadgeText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  content: { flex: 1, padding: 16 },
  filterRow: { flexDirection: 'row-reverse', gap: 8, marginBottom: 16 },
  filterBtn: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: '#fff',
    ...shadow({ offset: { width: 0, height: 1 }, opacity: 0.05, radius: 4, elevation: 2 }),
  },
  filterBtnActive: { backgroundColor: '#2E86AB' },
  filterText: { fontSize: 14, fontWeight: '600', color: '#6B7280' },
  filterTextActive: { color: '#fff' },
  loadingText: { textAlign: 'center', color: '#6B7280', marginTop: 24 },
  list: { flex: 1 },
  listContent: { paddingBottom: 40 },
  reportCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    ...shadow({ offset: { width: 0, height: 2 }, opacity: 0.08, radius: 6, elevation: 2 }),
  },
  reportStore: { fontSize: 16, fontWeight: '700', color: '#1F2937', textAlign: 'right' },
  reportReason: { fontSize: 14, color: '#6B7280', marginTop: 4, textAlign: 'right' },
  reportDetails: { fontSize: 13, color: '#9CA3AF', marginTop: 6, textAlign: 'right' },
  reportDate: { fontSize: 12, color: '#9CA3AF', marginTop: 8, textAlign: 'right' },
  reportActions: { flexDirection: 'row-reverse', gap: 8, marginTop: 12 },
  actionBtn: { paddingVertical: 6, paddingHorizontal: 14, borderRadius: 8 },
  actionBtnResolve: { backgroundColor: '#D1FAE5' },
  actionBtnDismiss: { backgroundColor: '#F3F4F6' },
  actionBtnText: { fontSize: 13, fontWeight: '600', color: '#374151' },
  statusBadge: { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, marginTop: 8 },
  statusResolved: { backgroundColor: '#D1FAE5' },
  statusDismissed: { backgroundColor: '#F3F4F6' },
  statusText: { fontSize: 12, fontWeight: '600', color: '#6B7280' },
  emptyState: { alignItems: 'center', paddingVertical: 40 },
  emptyStateEmoji: { fontSize: 48, marginBottom: 12 },
  emptyStateText: { color: '#9CA3AF', fontSize: 16 },
});
