import { StyleSheet } from 'react-native';
import { shadow } from '../../utils/shadowStyles';

export const adminCategoriesStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F0F4F8' },
  content: { flex: 1, padding: 16 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: '#1A3A5C', textAlign: 'right' },
  headerActions: { flexDirection: 'row-reverse', alignItems: 'center', gap: 10, flex: 1 },
  searchInput: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    fontSize: 14,
    color: '#1F2937',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    minWidth: 120,
  },
  addCategoryBtn: { backgroundColor: '#2E86AB', borderRadius: 10, paddingVertical: 8, paddingHorizontal: 14 },
  addCategoryBtnText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  list: { flex: 1 },
  listContent: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, paddingBottom: 40 },
  emptyState: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 60 },
  emptyStateEmoji: { fontSize: 60, marginBottom: 16 },
  emptyStateText: { color: '#9CA3AF', fontSize: 16, marginBottom: 16, textAlign: 'center' },
  emptyStateBtn: { backgroundColor: '#2E86AB', borderRadius: 12, paddingVertical: 12, paddingHorizontal: 24 },
  emptyStateBtnText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  categoryCard: {
    width: '31%',
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 14,
    borderWidth: 2,
    minWidth: 100,
    ...shadow({ offset: { width: 0, height: 2 }, opacity: 0.08, radius: 6, elevation: 2 }),
  },
  categoryCardIcon: { width: 44, height: 44, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginBottom: 8 },
  categoryCardEmoji: { fontSize: 24 },
  categoryCardName: { fontSize: 15, fontWeight: '700', color: '#1F2937', textAlign: 'right' },
  categoryCardCount: { fontSize: 12, color: '#6B7280', marginTop: 2, textAlign: 'right' },
  categoryCardActions: { flexDirection: 'column', gap: 6, marginTop: 10, alignItems: 'stretch' },
  categoryActionBtn: { paddingVertical: 6, paddingHorizontal: 12, borderRadius: 8 },
  categoryActionText: { fontSize: 12, fontWeight: '600', textAlign: 'center' },
  categoryActionBtnDel: { paddingVertical: 6, paddingHorizontal: 12, borderRadius: 8, backgroundColor: '#FEE2E2' },
  categoryActionTextDel: { fontSize: 12, fontWeight: '600', color: '#EF4444', textAlign: 'center' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  modal: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 24,
    width: '100%',
    maxWidth: 400,
    ...shadow({ offset: { width: 0, height: 4 }, opacity: 0.15, radius: 12, elevation: 10 }),
  },
  modalTitle: { fontSize: 18, fontWeight: '700', color: '#1A3A5C', textAlign: 'center', marginBottom: 16 },
  formLabel: { fontSize: 14, fontWeight: '600', color: '#374151', textAlign: 'right', marginBottom: 6 },
  formInput: {
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: '#1F2937',
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
  },
  colorRow: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 8, marginBottom: 16 },
  colorDot: { width: 32, height: 32, borderRadius: 16, borderWidth: 3, borderColor: 'transparent' },
  colorDotSelected: { borderColor: '#1F2937' },
  modalActions: { flexDirection: 'row-reverse', gap: 12 },
  confirmBtn: { flex: 1, backgroundColor: '#10B981', borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  confirmBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  cancelBtn: { flex: 1, backgroundColor: '#F3F4F6', borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  cancelBtnText: { color: '#6B7280', fontSize: 16, fontWeight: '600' },
  attrBackText: { fontSize: 15, fontWeight: '600', color: '#2E86AB' },
  attrHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    gap: 12,
    ...shadow({ offset: { width: 0, height: 2 }, opacity: 0.08, radius: 6, elevation: 2 }),
  },
  attrHeaderIcon: { width: 56, height: 56, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  attrHeaderTitle: { fontSize: 18, fontWeight: '700', color: '#1A3A5C', textAlign: 'right' },
  attrHeaderSub: { fontSize: 12, color: '#6B7280', textAlign: 'right', marginTop: 4 },
  addAttrBtn: { backgroundColor: '#2E86AB', borderRadius: 12, paddingVertical: 12, alignItems: 'center', marginBottom: 16 },
  addAttrBtnText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  attrTopActionsRow: {
    flexDirection: 'row-reverse',
    alignItems: 'stretch',
    gap: 10,
    marginBottom: 16,
  },
  attrTopActionHalf: {
    flex: 1,
    marginBottom: 0,
  },
  classificationTreeBtn: {
    backgroundColor: '#0F766E',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    marginBottom: 16,
  },
  classificationTreeBtnText: { color: '#fff', fontSize: 14, fontWeight: '700', textAlign: 'center' },
  classificationTreeCheckboxBtn: {
    backgroundColor: '#ECFEFF',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#99F6E4',
  },
  classificationTreeCheckboxBtnChecked: {
    backgroundColor: '#0F766E',
    borderColor: '#0F766E',
  },
  classificationTreeCheckboxText: { color: '#0F766E', fontSize: 13, fontWeight: '700', textAlign: 'center' },
  classificationTreeCheckboxTextChecked: { color: '#fff' },
  attrDefActions: { flexDirection: 'row-reverse', gap: 8, marginTop: 10, flexWrap: 'wrap', justifyContent: 'flex-end' },
  attrDefEditBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: '#E0E7FF',
  },
  attrDefEditText: { fontSize: 12, fontWeight: '600', color: '#4338CA', textAlign: 'center' },
  attrDefDelBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: '#FEE2E2',
  },
  attrDefDelText: { fontSize: 12, fontWeight: '600', color: '#DC2626', textAlign: 'center' },
  attrDefCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 16,
    marginBottom: 10,
    ...shadow({ offset: { width: 0, height: 1 }, opacity: 0.06, radius: 4, elevation: 2 }),
  },
  attrDefHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 8, marginBottom: 8 },
  attrDefLabel: { fontSize: 16, fontWeight: '700', color: '#1F2937', textAlign: 'right' },
  requiredBadge: { backgroundColor: '#FEF3C7', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 2 },
  requiredBadgeText: { fontSize: 11, fontWeight: '600', color: '#B45309' },
  attrDefMeta: { flexDirection: 'row', gap: 8, justifyContent: 'flex-end' },
  attrDefChip: { backgroundColor: '#F3F4F6', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 4 },
  attrDefChipText: { fontSize: 12, color: '#6B7280', fontWeight: '500' },
  valueTypeRow: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 8, marginBottom: 16 },
  valueTypeChip: { backgroundColor: '#F3F4F6', borderRadius: 10, paddingHorizontal: 14, paddingVertical: 8, borderWidth: 1.5, borderColor: '#E5E7EB' },
  valueTypeChipActive: { backgroundColor: '#2E86AB', borderColor: '#2E86AB' },
  valueTypeChipText: { fontSize: 14, color: '#374151', fontWeight: '500' },
  valueTypeChipTextActive: { color: '#fff', fontWeight: '700' },
  requiredToggle: { backgroundColor: '#F3F4F6', borderRadius: 12, padding: 14, marginBottom: 16, alignItems: 'center', borderWidth: 1.5, borderColor: '#E5E7EB' },
  requiredToggleActive: { backgroundColor: '#DCFCE7', borderColor: '#86EFAC' },
  requiredToggleText: { fontSize: 15, fontWeight: '600', color: '#374151' },
});
