import { StyleSheet } from 'react-native';
import { shadow } from '../../utils/shadowStyles';

export const adminClassificationTreeStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#E8EEF2' },
  scroll: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 32 },
  contentFlex: { flex: 1 },
  intro: { fontSize: 14, color: '#4B5563', textAlign: 'right', lineHeight: 22, marginBottom: 14 },
  sectorGrid: { flexDirection: 'row-reverse', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 12 },
  sectorCard: {
    width: '48.5%',
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#F3F4F6',
    ...shadow({ offset: { width: 0, height: 2 }, opacity: 0.08, radius: 8, elevation: 3 }),
  },
  sectorEmoji: { fontSize: 28, marginBottom: 8 },
  sectorLabel: { fontSize: 14, fontWeight: '700', color: '#1F2937', textAlign: 'center' },
  sectorHint: { fontSize: 11, color: '#9CA3AF', marginTop: 4, textAlign: 'center' },
  sectionHeader: { flexDirection: 'row-reverse', paddingHorizontal: 16, paddingTop: 12, paddingBottom: 4 },
  addBtn: {
    height: 42,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: '#2E86AB',
    alignItems: 'center',
    justifyContent: 'center',
    ...shadow({ offset: { width: 0, height: 2 }, opacity: 0.12, radius: 4, elevation: 3 }),
  },
  addBtnText: { color: '#fff', fontWeight: '800', fontSize: 14 },
  centerWrap: { paddingVertical: 40, alignItems: 'center' },
  loadingText: { marginTop: 12, color: '#6B7280', fontSize: 14 },
  emptyState: { alignItems: 'center', paddingVertical: 48 },
  emptyEmoji: { fontSize: 40, marginBottom: 8 },
  emptyText: { fontSize: 15, color: '#6B7280', textAlign: 'center' },
  mainBlock: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    ...shadow({ offset: { width: 0, height: 1 }, opacity: 0.06, radius: 4, elevation: 2 }),
  },
  mainRow: { flexDirection: 'row-reverse', alignItems: 'center', gap: 8, marginBottom: 6, flexWrap: 'wrap' },
  colorDotBig: { width: 12, height: 12, borderRadius: 6 },
  mainEmoji: { fontSize: 24 },
  mainName: { flex: 1, fontSize: 17, fontWeight: '800', color: '#111827', textAlign: 'right' },
  actionsRow: { flexDirection: 'row-reverse', gap: 8, marginBottom: 10 },
  actionBtn: { height: 34, paddingHorizontal: 12, borderRadius: 10, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
  actionText: { fontWeight: '800', fontSize: 12 },
  subBtn: { backgroundColor: '#EEF5FF', borderColor: '#C7DBF8' },
  editBtn: { backgroundColor: '#ECFAF1', borderColor: '#C8EED7' },
  delBtn: { backgroundColor: '#FEF1F1', borderColor: '#F8CACA' },
  subBtnText: { color: '#1E3A8A' },
  editBtnText: { color: '#065F46' },
  delBtnText: { color: '#991B1B' },
  noSubs: { fontSize: 13, color: '#9CA3AF', textAlign: 'right', fontStyle: 'italic', marginTop: 4 },
  subRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#F3F4F6',
  },
  subInfo: { flexDirection: 'row-reverse', alignItems: 'center', gap: 6, flex: 1 },
  subEmoji: { fontSize: 18 },
  subName: { fontSize: 15, color: '#374151', textAlign: 'right' },
  subActions: { flexDirection: 'row-reverse', gap: 14 },
  miniEditText: { fontSize: 12, fontWeight: '700', color: '#065F46' },
  miniDelText: { fontSize: 12, fontWeight: '700', color: '#991B1B' },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'center', padding: 20 },
  modalCard: { backgroundColor: '#fff', borderRadius: 16, padding: 16 },
  modalTitle: { fontSize: 16, fontWeight: '800', marginBottom: 10, textAlign: 'right' },
  input: {
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 12,
    backgroundColor: '#fff',
    marginBottom: 10,
    color: '#1F2937',
  },
  row2: { flexDirection: 'row-reverse', gap: 10 },
  halfInput: { flex: 1 },
  presetRow: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 10, alignItems: 'center', marginBottom: 10 },
  colorDot: { width: 22, height: 22, borderRadius: 11, borderWidth: 1, borderColor: '#E5E7EB' },
  colorDotActive: { borderColor: '#111827', borderWidth: 2 },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 6 },
  modalBtn: { flex: 1, height: 44, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  modalCancel: { backgroundColor: '#F3F4F6' },
  modalSave: { backgroundColor: '#2E86AB' },
  modalCancelText: { fontWeight: '800', color: '#374151' },
  modalSaveText: { fontWeight: '800', color: '#fff' },
});
